# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'verbose_name': 'Recording', 'verbose_name_plural': 'Recordings'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Sentence', 'verbose_name_plural': 'Sentences'},
        ),
    ]
