# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20161014_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'en_NZ', 'New Zealand English'), (b'mi', 'Maori')], default=b'en_NZ', max_length=16),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.CharField(help_text='The sentence to be spoken.', max_length=250, unique=True),
        ),
    ]
