# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20161019_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori'), (b'en_NZ', 'New Zealand English')], default=b'en_NZ', max_length=16),
        ),
    ]
