# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20161025_2216'),
        ('corpus', '0004_auto_20161025_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together=set([('person', 'sentence')]),
        ),
    ]
