# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20161014_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'en', 'English'), (b'en_NZ', 'New Zealand English'), (b'mi', 'Maori')], default=b'en_NZ', max_length=16)),
                ('level_of_proficiency', models.IntegerField(choices=[(1, 'Native Speaker - Beginner'), (2, 'Native Speaker - Intermediate'), (3, 'Native Speaker - Advanced'), (4, 'Near Native Speaker - Beginner'), (5, 'Near Native Speaker - Intermediate'), (6, 'Near Native Speaker - Advanced'), (7, 'Second Language Learner - Beginner'), (8, 'Second Language Learner - Intermediate'), (9, 'Second Language Learner - Advanced')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='age',
        ),
        migrations.AddField(
            model_name='demographic',
            name='birthday',
            field=models.DateField(blank=True, help_text='When were you born?', null=True),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('TF', 'Transexual (Male to Female)'), ('TM', 'Transexual (Female to Male)'), ('A', 'Asexual')], help_text='Gender', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='demographic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Demographic'),
        ),
        migrations.AddField(
            model_name='knownlanguage',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
