# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20161019_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='demographic',
        ),
        migrations.AddField(
            model_name='demographic',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='level_of_proficiency',
            field=models.IntegerField(choices=[(1, 'Native Speaker - Beginner'), (2, 'Native Speaker - Intermediate'), (3, 'Native Speaker - Advanced'), (4, 'Near Native Speaker - Beginner'), (5, 'Near Native Speaker - Intermediate'), (6, 'Near Native Speaker - Advanced'), (7, 'Second Language Learner - Beginner'), (8, 'Second Language Learner - Intermediate'), (9, 'Second Language Learner - Advanced')]),
        ),
    ]
