# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20161019_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownlanguage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knownlanguage',
            name='language',
            field=models.CharField(choices=[(b'mi', 'Maori'), (b'en_NZ', 'New Zealand English')], max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='knownlanguage',
            unique_together=set([('person', 'language')]),
        ),
    ]
